extensions:
  memory_ballast:
    size_mib: 512
  zpages:
    endpoint: 0.0.0.0:55679

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: otel-collector:4317

exporters:
  otlp/elastic:
    endpoint: {{APM_OTLP_ENDPOINT}}
    tls:
      insecure_skip_verify: true
    headers:
      Authorization: "Bearer {{APM_SECRET_TOKEN}}" 
  logging:
    loglevel: debug

service:
  extensions: [memory_ballast, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp/elastic, logging]
    metrics:
      receivers: [otlp]
      exporters: [otlp/elastic, logging]

